const robots = [
    {
        "series": 1,
        "id":0,
        "name": "Proto Man",
        "weapon":"Proto Buster",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/5/5f/MM3ProtoMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/1/19/ProtoColor.png",
        "weakness":"",
        "stageImg":"",
    },
    {
        "series": 1,
        "id":1,
        "name": "Mega Man",
        "weapon":"Mega Buster",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/2/26/MMLCdatamegamanMM3.png",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/b/bf/Megaman.png",
        "weakness":"",
        "stageImg":"",
    },
    {
        "series": 1,
        "id":2,
        "name": "Roll",
        "weapon":"None",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/f/fd/MM1Roll.png",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/1/15/Roll.png?20210815191147",
        "weakness":"",
        "stageImg":"",
    },
    {
        "series": 1,
        "id":3,
        "name": "Cut Man",
        "weapon":"Rolling Cutter",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/c/c4/MM-CutMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/2/22/Cutman.png",
        "weakness":"Super Arm",
        "stageImg":"https://static.wikia.nocookie.net/esmegaman/images/d/dd/CutMan-Mapa.png",
    },
    {
        "series": 1,
        "id":4,
        "name": "Guts Man",
        "weapon":"Super Arm",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/7/70/MM-GutsMan.jpg",        
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/6/60/Gutsman.png",
        "weakness":"Hyper Bomb",
        "stageImg":"https://static.wikia.nocookie.net/esmegaman/images/a/ac/GutsMan-Mapa.png",
    },
    {
        "series": 1,
        "id":5,
        "name": "Ice Man",
        "weapon":"Ice Slasher",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/0/04/MM-IceMan.jpg",        
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/6/61/IceMan.png",
        "weakness":"Thunder Beam",
        "stageImg":"https://static.wikia.nocookie.net/esmegaman/images/4/44/IceMan-Mapa.png",
    },
    {
        "series": 1,
        "id":6,
        "name": "Bomb Man",
        "weapon":"Hyper Bomb",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/b/b6/MM-BombMan.jpg",        
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/2/24/BombMan.png",
        "weakness":"Mega Buster",
        "stageImg":"https://static.wikia.nocookie.net/esmegaman/images/e/ec/BombMan-Mapa.png",
    },
    {
        "series": 1,
        "id":7,
        "name": "Fire Man",
        "weapon":"Fire Storm",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/d/d9/Original_FireMan.jpg",        
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/a/a9/FireMan.png",
        "weakness":"Ice Slasher",
        "stageImg":"https://static.wikia.nocookie.net/esmegaman/images/1/1b/FireMan-Mapa.png",
    },
    {
        "series": 1,
        "id":8,
        "name": "Elec Man",
        "weapon":"Thunder Beam",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/9/91/MM-ElecMan.jpg",        
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/e/ea/ElecMan.png",
        "weakness":"Rolling Cutter",
        "stageImg":"https://static.wikia.nocookie.net/esmegaman/images/3/3c/ElecMan-Mapa.png",
    },
    {
        "series": 2,
        "id":9,
        "name": "Metal Man",
        "weapon": "Metal Blade",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/2/26/MM2MetalMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/thumb/archive/1/19/20230303182334%21MetalMan.png/120px-MetalMan.png",
        "weakness": "Quick Boomerang/Metal Blade",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/3/37/MetalMan-Mapa.png"
    },
    {
        "series": 2,
        "id":10,
        "name": "Air Man",
        "weapon": "Air Blade",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/d/d0/MM2AirMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/3/30/AirMan.png",
        "weakness": "Leaf Shield",
        "stageImg": ""
    },
    {
        "series": 2,
        "id":11,
        "name": "Bubble Man",
        "weapon": "Bubble Lead",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/5/5a/MM2BubbleMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/0/03/BubbleMan.png",
        "weakness": "Metal Blade",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/3/31/BubbleMan-Mapa.png"
    },
    {
        "series": 2,
        "id":12,
        "name": "Quick Man",
        "weapon": "Quick Boomerang",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/9/91/MM2QuickMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/2/23/QuickMan.png",
        "weakness": "Time Stopper/Crash Bomber",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/9/91/MM2QuickMan.jpg"
    },
    {
        "series": 2,
        "id":13,
        "name": "Crash Man",
        "weapon": "Crash Bomber",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/d/d0/MM2ClashMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/d/dc/CrashMan.png",
        "weakness": "Air Shooter",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/0/0a/CrashMan-Mapa.png"
    },
    {
        "series": 2,
        "id":14,
        "name": "Flash Man",
        "weapon": "Time Stopper",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/8/8a/MM2FlashMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/0/09/FlashMan.png",
        "weakness": "Crash Bomber/Metal Blade",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/b/bc/FlashMan-Mapa.png/revision/latest/scale-to-width-down/1000?cb=20170107020520"
    },
    {
        "series": 2,
        "id":15,
        "name": "Heat Man",
        "weapon": "Atomic Fire",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/b/be/MM2HeatMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/1/1a/HeatMan.png",
        "weakness": "Bubble Lead",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/5/5a/HeatMan-Mapa.png"
    },
    {
        "series": 2,
        "id":16,
        "name": "Wood Man",
        "weapon": "Left Shield",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/4/4f/MM2WoodMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/3/32/WoodMan.png",
        "weakness": "Atomic Fire/Air Shooter",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/4/42/WoodMan-Mapa.png"
    },
    {
        "series": 3,
        "id":17,
        "name": "Needle Man",
        "weapon": "Needle Cannon",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/a/a3/MM3NeedleMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/7/7e/NeedleColor.png",
        "weakness": "Gemini Laser",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/e/e5/NeedleMan-Mapa.png"
    },
    {
        "series": 3,
        "id":18,
        "name": "Magnet Man",
        "weapon": "Magnet Missile",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/0/0a/MM3MagnetMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/d/d3/MagnetMan.png",
        "weakness": "Spark Shock",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/a/ad/MagnetMan-Mapa.png"
    },
    {
        "series": 3,
        "id":19,
        "name": "Gemini Man",
        "weapon": "Gemini Laser",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/4/4a/MM3GeminiMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/7/78/GeminiManMegaMan3.png",
        "weakness": "Search Snake",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/1/12/GeminiMan-Mapa.png"
    },
    {
        "series": 3,
        "id":20,
        "name": "Hard Man",
        "weapon": "Hard Knuckle",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/a/a9/MM3HardMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/8/89/HeavyMan.png",
        "weakness": "Magnet Missile",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/6/6a/HardMan-Mapa.png"
    },
    {
        "series": 3,
        "id":21,
        "name": "Top Man",
        "weapon": "Top Spin",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/7/70/MM3TopMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/b/bc/TopMan.png",
        "weakness": "Hard Knuckle",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/9/9e/TopMan-Mapa.png"
    },
    {
        "series": 3,
        "id":22,
        "name": "Snake Man",
        "weapon": "Search Snake",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/1/12/MM3SnakeMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/7/7b/SnakeMan.png",
        "weakness": "Needle Cannon",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/a/a3/SnakeMan-Mapa.png"
    },
    {
        "series": 3,
        "id":23,
        "name": "Spark Man",
        "weapon": "Spark Shork",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/e/ec/MM3SparkMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/d/d9/SparkNoTheOtherOne.png",
        "weakness": "Shadow Blade",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/a/a4/SparkMan-Mapa.png"
    },
    {
        "series": 3,
        "id":24,
        "name": "Shadow Man",
        "weapon": "Shadow Blade",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/4/41/MM3ShadowMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/5/54/ShadowMan.png",
        "weakness": "Top Spin",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/c/c7/ShadowMan-Mapa.png"
    },
    {
        "series": 4,
        "id":25,
        "name": "Bright Man",
        "weapon": "Flash Stopper",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/6/60/MM4-BrightMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/a/ac/BrightMan.png",
        "weakness": "Rain Flush",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/4/4e/BrightMan-Mapa.png"
    },
    {
        "series": 4,
        "id":26,
        "name": "Toad Man",
        "weapon": "Rain Flush",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/7/77/MM4-ToadMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/b/bf/Toadman.png",
        "weakness": "Drill Bomb",
        "stageImg": "https://static.wikia.nocookie.net/esmegaman/images/f/f1/ToadMan-Mapa.png"
    },
    {
        "series": 4,
        "id":27,
        "name": "Drill Man",
        "weapon": "Drill Bomb",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/c/cb/MM4-DrillMan.jpg",        
        "sprite1": "http://vignette2.wikia.nocookie.net/megaman/images/2/25/Drillsprite.png",
        "weakness": "Dive Missile",
        "stageImg": ""
    },
    {
        "series": 4,
        "id":28,
        "name": "Pharaoh Man",
        "weapon": "Pharaoh Shot",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/d/d4/MM4-PharaohMan.jpg",        
        "sprite1": "http://vignette3.wikia.nocookie.net/megaman/images/b/bb/Pharaohsprite.png",
        "weakness": "Flash Stopper",
        "stageImg": ""
    },
    {
        "series": 4,
        "id":29,
        "name": "Ring Man",
        "weapon": "Ring Boomerang",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/6/6c/MM4-RingMan.jpg",        
        "sprite1": "http://vignette2.wikia.nocookie.net/megaman/images/b/b3/MM10WA4.png",
        "weakness": "Pharaoh Shot",
        "stageImg": ""
    },
    {
        "series": 4,
        "id":30,
        "name": "Dust Man",
        "weapon": "Dust Crusher",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/e/e9/MM4-DustMan.jpg",        
        "sprite1": "http://vignette1.wikia.nocookie.net/megaman/images/4/41/Dustsprite.png",
        "weakness": "Ring Boomerang",
        "stageImg": ""
    },
    {
        "series": 4,
        "id":31,
        "name": "Dive Man",
        "weapon": "Dive Missile",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/3/3e/MM4-DiveMan.jpg",        
        "sprite1": "http://vignette2.wikia.nocookie.net/megaman/images/d/df/Divesprite.png",
        "weakness": "Skull Barrier",
        "stageImg": ""
    },
    {
        "series": 4,
        "id":32,
        "name": "Skull Man",
        "weapon": "Skull Barrier",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/e/eb/MM4-SkullMan.jpg",        
        "sprite1": "http://vignette3.wikia.nocookie.net/megaman/images/e/e8/Skullsprite.png",
        "weakness": "Dust Crusher",
        "stageImg": ""
    },
    {
        "series": 5,
        "id":33,
        "name": "Gravity Man",
        "weapon": "Gravity Hold",
        "avatar": "https://th.bing.com/th/id/R.5f76bae9e9407baf90b81b1a7b0e5fd2?rik=uObE%2bPFKv6lzKQ&riu=http%3a%2f%2fimages.wikia.com%2fmegaman%2fimages%2f1%2f17%2fMM5-GravityMan.jpg&ehk=%2fxUDtdSftBxHx8yq8FiCtu0U4PBTktgRSqZGV%2b3oo9M%3d&risl=&pid=ImgRaw&r=0",
        "sprite1": "http://vignette1.wikia.nocookie.net/megaman/images/9/9d/Gravitysprite.png",
        "weakness": "Star Crash",
        "stageImg": ""
    },
    {
        "series": 5,
        "id":34,
        "name": "Wave Man",
        "weapon": "Water Wave",
        "avatar": "https://th.bing.com/th/id/R.de67dcb54da81a71da072addeae3f9e6?rik=GdCQKCt%2fs5ZFqg&riu=http%3a%2f%2fimg2.wikia.nocookie.net%2f__cb20110413195201%2fmegaman%2fimages%2fthumb%2fc%2fc9%2fMM5-WaveMan.jpg%2f500px-MM5-WaveMan.jpg&ehk=XEnG4OcsME8CT2EHp5cyWseXIhRyga1ZqHSs0UWZzeU%3d&risl=&pid=ImgRaw&r=0",        
        "sprite1": "http://vignette2.wikia.nocookie.net/megaman/images/c/cc/Wavesprite.png",
        "weakness": "Charge Kick",
        "stageImg": ""
    },
    {
        "series": 5,
        "id":35,
        "name": "Stone Man",
        "weapon": "Power Stone",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/7/79/MM5-StoneMan.jpg",        
        "sprite1": "http://vignette2.wikia.nocookie.net/megaman/images/a/ab/Stonesprite.png",
        "weakness": "Napalm Bomb",
        "stageImg": ""
    },
    {
        "series": 5,
        "id":36,
        "name": "Gyro Man",
        "weapon": "Gyro Attack",
        "avatar": "https://vignette2.wikia.nocookie.net/megaman/images/3/32/MM5-GyroMan.jpg/revision/latest?cb=20110413230520",        
        "sprite1": "http://vignette3.wikia.nocookie.net/megaman/images/c/c3/Gyrosprite.png",
        "weakness": "Gravity Hold",
        "stageImg": ""
    },
    {
        "series": 5,
        "id":37,
        "name": "Star Man",
        "weapon": "Star Crash",
        "avatar": "https://tse4.mm.bing.net/th/id/OIP.RYydP17aksDLy-Ad67btYgAAAA?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3",        
        "sprite1": "http://vignette2.wikia.nocookie.net/megaman/images/7/70/Starsprite.png",
        "weakness": "Water Wave",
        "stageImg": ""
    },
    {
        "series": 5,
        "id":38,
        "name": "Charge Man",
        "weapon": "Charge Kick",
        "avatar": "https://th.bing.com/th/id/R.6880969653e418aa693e08c27157d12c?rik=q%2fRIYQ%2bSu5ssGw&riu=http%3a%2f%2fvignette3.wikia.nocookie.net%2fmegaman%2fimages%2f7%2f75%2fMM5-ChargeMan.jpg%2frevision%2flatest%3fcb%3d20110425062042&ehk=vlzb%2bm1WiD1TtLZFfBXBE%2f7AMJoYHOJbF9QfsiJGHf4%3d&risl=&pid=ImgRaw&r=0",        
        "sprite1": "http://vignette4.wikia.nocookie.net/megaman/images/1/1a/Chargesprite.png",
        "weakness": "Power Stone",
        "stageImg": ""
    },
    {
        "series": 5,
        "id":39,
        "name": "Napalm Man",
        "weapon": "Napalm Bomb",
        "avatar": "https://tse3.mm.bing.net/th/id/OIP.ewT9xajv0V7zypgKqxqa6gHaF-?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3",        
        "sprite1": "http://vignette2.wikia.nocookie.net/megaman/images/a/aa/MM10WA5.png",
        "weakness": "Crystal Eye",
        "stageImg": ""
    },    
    {
        "series": 5,
        "id":40,
        "name": "Crystal Man",
        "weapon": "Napalm Bomb",
        "avatar": "https://tse4.mm.bing.net/th/id/OIP.4Ot2b-ceDrPDBtw6_fSAiAHaHd?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3",
        "sprite1": "http://vignette2.wikia.nocookie.net/megaman/images/c/ce/Crystalsprite.png",
        "weakness": "Gyro Attack",
        "stageImg": ""
    },
    {
        "series": 6,
        "id":41,
        "name": "Blizzard Man",
        "weapon": "Blizzard Attack",
        "avatar": "https://static.wikia.nocookie.net/esmegaman/images/1/10/MM6-BlizzardMan.jpg",
        "sprite1": "https://static.miraheze.org/ccbmwikiwiki/4/4f/BlizzardMan.png",
        "weakness": "Gyro Attack",
        "stageImg": ""
    },
    {
        "series":6,
        "id":42,
        "name":"Flame Man",
        "weapon": "Flame Blast",
        "avatar":"https://tse4.mm.bing.net/th/id/OIP.2f50gi9oJXLBKIld5p1waAHaI5?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3",
        "sprite1":"https://i.ytimg.com/vi/XSByIYtxKI8/hqdefault.jpg",
        "weakness":"Wind Storm",
        "stageImg":""
    },
    {
        "series":6,
        "id":43,
        "name":"Plant Man",
        "weapon": "Plant Barrier",
        "avatar":"https://th.bing.com/th/id/R.e59219b4da28d775202c1d42d4866298?rik=%2bspffjWEGuqBKQ&riu=http%3a%2f%2fvignette3.wikia.nocookie.net%2fmegaman%2fimages%2f4%2f42%2fMM6-PlantMan.jpg%2frevision%2flatest%3fcb%3d20110427032726&ehk=EVw0pqEsCMC8J1e6IbHfDwNJduqrm%2bPiBb92%2bl6BRCw%3d&risl=&pid=ImgRaw&r=0",
        "sprite1":"https://static.wikitide.net/ccbmwikiwiki/c/c6/PlantMan.png",
        "weakness":"Flame Blase",
        "stageImg":""
    },
    {
        "series":6,
        "id":44,
        "name":"Tomahawk Man",
        "weapon": "Silver Tomahawk",
        "avatar":"https://th.bing.com/th/id/R.b412df7913f7896621be0d139e910f2c?rik=ANNd8EKpzhQzQw&riu=http%3a%2f%2fgonintendo.com%2fsystem%2ffile_uploads%2fuploads%2f000%2f007%2f405%2foriginal%2f51f62e33a46fa6309198c7013dd055e0.png&ehk=7UN96yk1yMaFyUmKG4y5RfSK6Im68ixAaMAiEMnxfgE%3d&risl=&pid=ImgRaw&r=0",
        "sprite1":"https://static.wikitide.net/ccbmwikiwiki/a/a3/TomahawkMan.png",
        "weakness":"Plant Barrier",
        "stageImg":""
    },
    {
        "series":6,
        "id":45,
        "name":"Yamato Man",
        "weapon": "Yamato Spear",
        "avatar":"https://tse2.mm.bing.net/th/id/OIP.S9zYd0PbPA-xgYXimL7WlgHaFp?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3",
        "sprite1":"https://static.wikitide.net/ccbmwikiwiki/c/c1/YamatoMan.png",
        "weakness":"Silver Tomahawk",
        "stageImg":""
    },
    {
        "series":6,
        "id":46,
        "name":"Knight Man",
        "weapon": "Knight Crush",
        "avatar":"https://vignette4.wikia.nocookie.net/megaman/images/7/73/MM6-KnightMan.jpg/revision/latest?cb=20110426075433",
        "sprite1":"https://static.wikitide.net/ccbmwikiwiki/5/5b/KnightMan.png",
        "weakness":"Yamato Spear",
        "stageImg":""
    },
    {
        "series":6,
        "id":47,
        "name":"Centaur Man",
        "weapon": "Centaur Flash",
        "avatar":"https://tse4.mm.bing.net/th/id/OIP.t4O9d-GF9ccK_9Tl5gGnlQHaIE?cb=12&rs=1&pid=ImgDetMain&o=7&rm=3",
        "sprite1":"https://static.wikitide.net/ccbmwikiwiki/0/07/CentaurMan.png",
        "weakness":"Knight Crush",
        "stageImg":""
    },
    {
        "series":6,
        "id":48,
        "name":"Wind Man",
        "weapon": "Wind Storm",
        "avatar":"https://static.wikia.nocookie.net/esmegaman/images/d/d2/MM6-WindMan.jpg",
        "sprite1":"https://static.wikitide.net/ccbmwikiwiki/9/9d/WindMan.png",
        "weakness":"Centaur Flash",
        "stageImg":""
    }
];



module.exports = {
    robots
}